config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, :only => [:edit, :update]
    resource  :alias_and_implication_import, :only => [:new, :create]
    resource  :dashboard, :only => [:show]
  end
  namespace :mobile do
    resources :posts, :only => [:index, :show]
  end
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :search
      end
    end
    resources :invitations, :only => [:new, :create, :index]
    resource :tag, :only => [:edit, :update]
    namespace :post do
      resource :queue, :only => [:show]
      resource :approval, :only => [:create]
      resource :disapproval, :only => [:create]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
        end
      end
    end
    resources :invitations, :only => [:new, :create, :index, :show]
    resources :ip_addrs, :only => [:index, :search] do
      collection do
        get :search
      end
    end
  end
  namespace :explore do
    resources :posts do
      collection do
        get :popular
        get :searches
        get :missed_searches
        get :hot
        get :intro
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
    end
  end

  resources :advertisements do
    resources :hits, :controller => "advertisement_hits", :only => [:create]
  end
  resources :api_keys, :only => [:new, :create]
  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
      post :undelete
    end
    collection do
      get :show_or_new
      get :banned
      get :finder
    end
  end
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resources :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
      get :index_all
    end
    member do
      put :unvote
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :delayed_jobs, :only => [:index]
  resources :dmails do
    collection do
      get :search
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :favorites
  resources :favorite_groups do
    member do
      put :add_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :undelete
      get :new_merge
      post :create_merge
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :ip_bans
  resources :iqdb_queries, :only => [:create]
  resources :janitor_trials do
    collection do
      get :test
    end
    member do
      put :promote
      put :demote
    end
  end
  resources :jobs
  resource :landing
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource  :pool_element, :only => [:create, :destroy] do
    collection do
      get :all_select
    end
  end
  resources :pool_versions, :only => [:index]
  resources :posts do
    resources :events, :only => [:index], :controller => "post_events"
    resources :votes, :controller => "post_votes", :only => [:create, :destroy]
    collection do
      get :home
      get :random
    end
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :unvote
      put :mark_as_translated
    end
  end
  resources :post_appeals
  resources :post_flags
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index]
  resource :related_tag, :only => [:show, :update]
  get "reports/user_promotions" => "reports#user_promotions"
  get "reports/janitor_trials" => "reports#janitor_trials"
  get "reports/contributors" => "reports#contributors"
  get "reports/uploads" => "reports#uploads"
  get "reports/similar_users" => "reports#similar_users"
  get "reports/post_versions" => "reports#post_versions"
  post "reports/post_versions_create" => "reports#post_versions_create"
  resources :saved_searches, :except => [:show] do
    collection do
      get :categories
    end
  end
  resource :session do
    collection do
      get :sign_out
    end
  end
  resource :source, :only => [:show]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
    end
  end
  resources :tag_aliases do
    resource :correction, :controller => "tag_alias_corrections"
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :tag_subscriptions do
    member do
      post :migrate
      get :posts
    end
  end
  resources :uploads do
    collection do
      get :batch
      get :image_proxy
    end
  end
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"

    collection do
      get :search
      get :custom_style
    end

    member do
      delete :cache
    end
  end
  resource :user_upgrade, :only => [:new, :create, :show]
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests do
    member do
      post :approve
      post :reject
    end
  end
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"
  get "/m/posts", :controller => "mobile/posts", :action => "index"
  get "/m/posts/:id", :controller => "mobile/posts", :action => "show"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index.xml", :controller => "legacy", :action => "artists", :format => "xml"
  get "/artist/index.json", :controller => "legacy", :action => "artists", :format => "json"
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

  get "/favorite" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/index" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/list_users.json", :controller => "legacy", :action => "unavailable"

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/index" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}
  get "/forum/search" => redirect("/forum_posts/search")

  get "/help/:title" => redirect {|params, req| ("/wiki_pages?title=#{CGI::escape('help:' + req.params[:title])}")}

  get "/note" => redirect {|params, req| "/notes?page=#{req.params[:page]}"}
  get "/note/index" => redirect {|params, req| "/notes?page=#{req.params[:page]}"}
  get "/note/history" => redirect {|params, req| "/note_versions?search[updater_id]=#{req.params[:user_id]}"}

  get "/pool" => redirect {|params, req| "/pools?page=#{req.params[:page]}"}

app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController
  respond_to :html, :xml, :json, :js
  before_filter :member_only, :except => [:index, :show, :show_or_new]
  before_filter :moderator_only, :only => [:destroy]
  before_filter :normalize_search_params, :only => [:index]
  rescue_from ActiveRecord::StatementInvalid, :with => :rescue_exception
  rescue_from ActiveRecord::RecordNotFound, :with => :rescue_exception
  
  def new
    @wiki_page = WikiPage.new(params[:wiki_page])
    respond_with(@wiki_page)
  end

  def edit
    @wiki_page = WikiPage.find(params[:id])
    respond_with(@wiki_page)
  end

  def index
    @wiki_pages = WikiPage.search(params[:search]).order("updated_at desc").paginate(params[:page], :limit => params[:limit], :search_count => params[:search])
    respond_with(@wiki_pages) do |format|
      format.html do
        if params[:page].nil? || params[:page].to_i == 1
          if @wiki_pages.count == 1
            redirect_to(wiki_page_path(@wiki_pages.first))
          elsif @wiki_pages.count == 0 && params[:search][:title].present? && params[:search][:title] !~ /\*/
            redirect_to(wiki_pages_path(:search => {:title => "*#{params[:search][:title]}*"}))
          end
        end
      end
      format.xml do
        render :xml => @wiki_pages.to_xml(:root => "wiki-pages")
      end
    end
  end

  def show
    if params[:id] =~ /\A\d+\Z/
      @wiki_page = WikiPage.find(params[:id])
    else
      @wiki_page = WikiPage.find_by_title(params[:id])
      if @wiki_page.nil?
        redirect_to show_or_new_wiki_pages_path(:title => params[:id])
        return
      end
    end
    
    respond_with(@wiki_page)
  end

  def create
    @wiki_page = WikiPage.create(params[:wiki_page])
    respond_with(@wiki_page)
  end

  def update
    @wiki_page = WikiPage.find(params[:id])
    @wiki_page.update_attributes(params[:wiki_page])
    respond_with(@wiki_page)
  end

  def destroy
    @wiki_page = WikiPage.find(params[:id])
    @wiki_page.destroy
    respond_with(@wiki_page)
  end

  def revert
    @wiki_page = WikiPage.find(params[:id])
    @version = WikiPageVersion.find(params[:version_id])
    @wiki_page.revert_to!(@version)
    flash[:notice] = "Page was reverted"
    respond_with(@wiki_page)
  end

  def show_or_new
    @wiki_page = WikiPage.find_by_title(params[:title])
    if @wiki_page
      redirect_to wiki_page_path(@wiki_page)
    else
      @wiki_page = WikiPage.new(:title => params[:title])
      @artist = Artist.named(@wiki_page.title).active.first
      respond_with(@wiki_page)
    end
  end

private
  def normalize_search_params
    if params[:title]
      params[:search] ||= {}
      params[:search][:title] = params.delete(:title)
    end
  end
end

app/helpers/wiki_pages_helper.rb
module WikiPagesHelper
  def wiki_page_alias_and_implication_list(wiki_page)
    antecedent_alias = wiki_page.presenter.antecedent_tag_alias
    consequent_aliases = wiki_page.presenter.consequent_tag_aliases
    antecedent_implications = wiki_page.presenter.antecedent_tag_implications
    consequent_implications = wiki_page.presenter.consequent_tag_implications

    alias_and_implication_list(antecedent_alias, consequent_aliases, antecedent_implications, consequent_implications)
  end

  def wiki_page_post_previews(wiki_page)
    html = '<div id="wiki-page-posts">'

    if Post.fast_count(wiki_page.title) > 0
      full_link = link_to("view all", posts_path(:tags => wiki_page.title))
      html << "<h2>Posts (#{full_link})</h2>"
      html << wiki_page.post_set.presenter.post_previews_html(self)
    end
    
    html << "</div>"

    html.html_safe
  end

  def wiki_page_other_names_list(wiki_page)
    names_html = wiki_page.other_names_array.map{|name| link_to(name, "http://www.pixiv.net/search.php?s_mode=s_tag_full&word=#{u(name)}", :class => "other-name")}
    names_html.join(" ").html_safe
  end
end

app/views/wiki_pages/_form.html.erb
<div id="form-content">
  <%= error_messages_for("wiki_page") %>

  <%= simple_form_for(@wiki_page) do |f| %>
    <div class="input">
      <label for="wiki_page_title">Title</label>
      <% if @wiki_page.new_record? %>
        <%= text_field "wiki_page", "title" %>
      <% elsif CurrentUser.user.is_builder? %>
        <%= text_field "wiki_page", "title" %>
        <span class="hint">Change to rename this wiki page</span>
      <% else %>
        <p><%= @wiki_page.title %></p>
      <% end %>
    </div>

    <%= f.input :other_names, :as => :text, :label => "Other names (<a href='/wiki_pages/help:translated_tags'>view help</a>)".html_safe, :hint => "Names used for this tag on other sites such as Pixiv. Separate with spaces." %>

    <%= dtext_field "wiki_page", "body" %>

    <% if CurrentUser.is_moderator? %>
      <%= f.input :is_locked %>
    <% end %>

    <%= f.button :submit, "Submit" %>
    <%= dtext_preview_button "wiki_page", "body" %>
  <% end %>
</div>

app/views/wiki_pages/_quick_search.html.erb
<%= form_tag(wiki_pages_path, :method => :get) do %>
  <%= text_field "search", "title", :id => "quick_search_title", :placeholder => "Search wiki pages" %>
<% end %>

app/views/wiki_pages/_recent_changes.html.erb
<section>
  <h1>Recent Changes (<%= link_to "all", wiki_pages_path(:order => "time") %>)</h1>
  <ul>
    <% WikiPage.recent.each do |page| %>
      <li class="category-<%= page.category_name %>"><%= link_to page.pretty_title, wiki_page_path(page) %></li>
    <% end %>
  </ul>
</section>

app/views/wiki_pages/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <menu>
    <li><%= render "wiki_pages/quick_search" %></li>
    <li><%= link_to "Listing", wiki_pages_path %></li>
    <li><%= link_to "Search", search_wiki_pages_path %></li>
    
    <% if CurrentUser.is_member? %>
      <li><%= link_to "New", new_wiki_page_path %></li>
    <% end %>
    
    <li><%= link_to "Help", wiki_pages_path(:search => {:title => "help:wiki"}) %></li>
    
    <% if @wiki_page %>
      <li>|</li>
      <li><%= link_to "Posts (#{Post.fast_count(@wiki_page.title)})", posts_path(:tags => @wiki_page.title) %></li>
      <% unless @wiki_page.new_record? %>
        <li><%= link_to "History", wiki_page_versions_path(:search => {:wiki_page_id => @wiki_page.id}) %></li>
        <% if CurrentUser.is_member? %>
          <li><%= link_to "Edit", edit_wiki_page_path(@wiki_page), :id => "wiki-page-edit-link" %></li>
        <% end %>
        <% if CurrentUser.is_moderator? %>
          <li><%= link_to "Delete", wiki_page_path(@wiki_page), :remote => true, :method => :delete, :data => {:confirm => "Are you sure you want to delete this wiki page?"} %></li>
        <% end %>
      <% end %>
    <% end %>
    <% if @wiki_page_version %>
      <li>|</li>
      <li><%= link_to "Newest", wiki_page_path(@wiki_page_version.wiki_page_id) %></li>
      <% if CurrentUser.is_member? %>
        <li><%= link_to "Revert to", revert_wiki_page_path(@wiki_page_version.wiki_page_id, :version_id => @wiki_page_version.id), :method => :put, :data => {:confirm => "Are you sure you want to revert to this version?"} %></li>
      <% end %>
    <% end %>
  </menu>
<% end %>

app/views/wiki_pages/_sidebar.html.erb
<aside id="sidebar">
  <%= render "wiki_pages/recent_changes" %>

  <section id="blacklist-box">
    <h1>Blacklisted</h1>
    <ul id="blacklist-list">
    </ul>
  </section>
</aside>

app/views/wiki_pages/destroy.js.erb
window.location.href = "/wiki_pages";

app/views/wiki_pages/edit.html.erb
<div id="c-wiki-pages">
  <div id="a-edit">
    <%= render "sidebar" %>

    <section id="content">
      <h1>Edit Wiki</h1>

      <% if @wiki_page.visible? %>
        <%= render "form" %>
      <% else %>
        <p>The artist requested removal of this page.</p>
      <% end %>
    </section>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Edit Wiki Page - <%= Danbooru.config.app_name %>
<% end %>

app/views/wiki_pages/index.html.erb
<div id="c-wiki-pages">
  <div id="a-index">
    <%= render "sidebar" %>

    <section id="content">
      <h1>Wiki</h1>

      <table class="striped" width="100%">
        <thead>
          <tr>
            <th>Title</th>
            <th>Last edited</th>
          </tr>
        </thead>
        <tbody>
          <% @wiki_pages.each do |wiki_page| %>
            <tr>
              <td class="category-<%= wiki_page.category_name %>"><%= link_to wiki_page.pretty_title, wiki_page_path(wiki_page, :noredirect => 1) %></td>
              <td><%= wiki_page.updated_at.strftime("%Y-%m-%d %I:%M") %> by <%= h link_to_user wiki_page.updater %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= numbered_paginator(@wiki_pages) %>
    </section>
  </div>
</div>

<% content_for(:page_title) do %>
  Wiki - <%= Danbooru.config.app_name %>
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/new.html.erb
<div id="c-wiki-pages">
  <div id="a-new">
    <%= render "sidebar" %>

    <section id="content">
      <h1>New Wiki Page</h1>

      <% if @wiki_page.title.present? %>
        <div class="ui-corner-all ui-state-highlight notice">
          This wiki page does not yet exist. The form below will allow you to create a new page for <%= @wiki_page.title %>. It will act as an explanation on how to use the tag for other users on the site.
        </div>
      <% end %>

      <%= render "form" %>

      <%= wiki_page_alias_and_implication_list(@wiki_page)%>

      <%#= wiki_page_post_previews(@wiki_page) %>

      <div class="clearfix"></div>

    </section>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  New Wiki Page - <%= Danbooru.config.app_name %>
<% end %>

app/views/wiki_pages/search.html.erb
<div id="c-wiki-pages">
  <div id="a-search">
    <%= form_tag(wiki_pages_path, :method => :get, :class => "simple_form") do %>
      <%= search_field "title", :hint => "Use * for wildcard searches" %>
      <%= search_field "creator_name" %>
      <%= search_field "body_matches", :label => "Body" %>
      <%= search_field "other_names_match", :label => "Other names" %>

      <div class="input">
        <label for="search_other_names_present">Other names present?</label>
        <%= select "search", "other_names_present", ["yes", "no"], :include_blank => true %>
      </div>

      <div class="input">
        <label for="search_order">Order</label>
        <%= select "search", "order", ["Name", "Date"] %>
      </div>

      <%= submit_tag "Search" %>
    <% end %>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Search Wiki - <%= Danbooru.config.app_name %>
<% end %>

app/views/wiki_pages/show.html.erb
<div id="c-wiki-pages">
  <div id="a-show">
    <%= render "sidebar" %>

    <section id="content">
      <h1 id="wiki-page-title">

        <%= link_to @wiki_page.pretty_title, posts_path(:tags => @wiki_page.title), :class => "tag-type-#{@wiki_page.category_name}" %>

        <% if @wiki_page.is_locked? %>
          (locked)
        <% end %>
      </h1>

      <div id="wiki-page-body" class="prose">
        <% if @wiki_page.visible? %>
          <% if @wiki_page.other_names.present? %>
            <p><%= wiki_page_other_names_list(@wiki_page) %></p>
          <% end %>

          <%= format_text(@wiki_page.body) %>

          <% if @wiki_page.artist %>
            <p><%= link_to "View artist", @wiki_page.artist %></p>
          <% end %>

          <%= wiki_page_alias_and_implication_list(@wiki_page) %>
        <% else %>
          <p>This artist has requested removal of their information.</p>
        <% end %>
      </div>

        <%#= wiki_page_post_previews(@wiki_page) %>
    </section>
  </div>
</div>

<% content_for(:page_title) do %>
  Wiki - <%= @wiki_page.pretty_title %> - <%= Danbooru.config.app_name %>
<% end %>

<% content_for(:html_header) do %>
  <meta name="description" content="<%= @wiki_page.presenter.blurb %>"></meta>
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/show_or_new.html.erb
<div id="c-wiki-pages">
  <div id="a-show">
    <%= render "sidebar" %>

    <section id="content">
      <h1 id="wiki-page-title">
        <%= link_to @wiki_page.pretty_title, posts_path(:tags => @wiki_page.title), :class => "tag-type-#{@wiki_page.category_name}" %>
      </h1>
      <div id="wiki-page-body" class="prose">
        <p>This wiki page does not exist. <%= link_to "Create new wiki page", new_wiki_page_path(:wiki_page => {:title => params[:title]}) %>.</p>
      </div>

      <% if @artist %>
        <p><%= link_to "View artist", @artist %></p>
      <% end %>

      <%= wiki_page_alias_and_implication_list(@wiki_page)%>

      <%#= wiki_page_post_previews(@wiki_page) %>
    </section>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Wiki - <%= params[:title] %> - <%= Danbooru.config.app_name %>
<% end %>