config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, :only => [:edit, :update]
    resource  :alias_and_implication_import, :only => [:new, :create]
    resource  :dashboard, :only => [:show]
  end
  namespace :mobile do
    resources :posts, :only => [:index, :show]
  end
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :search
      end
    end
    resources :invitations, :only => [:new, :create, :index]
    resource :tag, :only => [:edit, :update]
    namespace :post do
      resource :queue, :only => [:show]
      resource :approval, :only => [:create]
      resource :disapproval, :only => [:create]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
        end
      end
    end
    resources :invitations, :only => [:new, :create, :index, :show]
    resources :ip_addrs, :only => [:index, :search] do
      collection do
        get :search
      end
    end
  end
  namespace :explore do
    resources :posts do
      collection do
        get :popular
        get :searches
        get :missed_searches
        get :hot
        get :intro
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
    end
  end

  resources :advertisements do
    resources :hits, :controller => "advertisement_hits", :only => [:create]
  end
  resources :api_keys, :only => [:new, :create]
  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
      post :undelete
    end
    collection do
      get :show_or_new
      get :banned
      get :finder
    end
  end
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resources :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
      get :index_all
    end
    member do
      put :unvote
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :delayed_jobs, :only => [:index]
  resources :dmails do
    collection do
      get :search
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :favorites
  resources :favorite_groups do
    member do
      put :add_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :undelete
      get :new_merge
      post :create_merge
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :ip_bans
  resources :iqdb_queries, :only => [:create]
  resources :janitor_trials do
    collection do
      get :test
    end
    member do
      put :promote
      put :demote
    end
  end
  resources :jobs
  resource :landing
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource  :pool_element, :only => [:create, :destroy] do
    collection do
      get :all_select
    end
  end
  resources :pool_versions, :only => [:index]
  resources :posts do
    resources :events, :only => [:index], :controller => "post_events"
    resources :votes, :controller => "post_votes", :only => [:create, :destroy]
    collection do
      get :home
      get :random
    end
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :unvote
      put :mark_as_translated
    end
  end
  resources :post_appeals
  resources :post_flags
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index]
  resource :related_tag, :only => [:show, :update]
  get "reports/user_promotions" => "reports#user_promotions"
  get "reports/janitor_trials" => "reports#janitor_trials"
  get "reports/contributors" => "reports#contributors"
  get "reports/uploads" => "reports#uploads"
  get "reports/similar_users" => "reports#similar_users"
  get "reports/post_versions" => "reports#post_versions"
  post "reports/post_versions_create" => "reports#post_versions_create"
  resources :saved_searches, :except => [:show] do
    collection do
      get :categories
    end
  end
  resource :session do
    collection do
      get :sign_out
    end
  end
  resource :source, :only => [:show]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
    end
  end
  resources :tag_aliases do
    resource :correction, :controller => "tag_alias_corrections"
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :tag_subscriptions do
    member do
      post :migrate
      get :posts
    end
  end
  resources :uploads do
    collection do
      get :batch
      get :image_proxy
    end
  end
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"

    collection do
      get :search
      get :custom_style
    end

    member do
      delete :cache
    end
  end
  resource :user_upgrade, :only => [:new, :create, :show]
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests do
    member do
      post :approve
      post :reject
    end
  end
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"
  get "/m/posts", :controller => "mobile/posts", :action => "index"
  get "/m/posts/:id", :controller => "mobile/posts", :action => "show"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index.xml", :controller => "legacy", :action => "artists", :format => "xml"
  get "/artist/index.json", :controller => "legacy", :action => "artists", :format => "json"
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

  get "/favorite" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/index" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/list_users.json", :controller => "legacy", :action => "unavailable"

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/index" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}
  get "/forum/search" => redirect("/forum_posts/search")

  get "/help/:title" => redirect {|params, req| ("/wiki_pages?title=#{CGI::escape('help:' + req.params[:title])}")}

  get "/note" => redirect {|params, req| "/notes?page=#{req.params[:page]}"}
  get "/note/index" => redirect {|params, req| "/notes?page=#{req.params[:page]}"}
  get "/note/history" => redirect {|params, req| "/note_versions?search[updater_id]=#{req.params[:user_id]}"}

  get "/pool" => redirect {|params, req| "/pools?page=#{req.params[:page]}"}

app/controllers/moderator/tags_controller.rb
module Moderator
  class TagsController < ApplicationController
    before_filter :moderator_only
    rescue_from TagBatchChange::Error, :with => :error

    def edit
    end

    def update
      Delayed::Job.enqueue(TagBatchChange.new(params[:tag][:antecedent], params[:tag][:consequent], CurrentUser.user.id, CurrentUser.ip_addr), :queue => "default")
      redirect_to edit_moderator_tag_path, :notice => "Post changes queued"
    end

    def error
      redirect_to edit_moderator_tag_path, :notice => "Error"
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :member_only, :only => [:edit, :update]
  respond_to :html, :xml, :json

  def edit
    @tag = Tag.find(params[:id])
    check_privilege(@tag)
    respond_with(@tag)
  end

  def index
    @tags = Tag.search(params[:search]).paginate(params[:page], :limit => params[:limit], :search_count => params[:search])
    respond_with(@tags) do |format|
      format.xml do
        render :xml => @tags.to_xml(:root => "tags")
      end
    end
  end

  def autocomplete
    @tags = Tag.names_matches_with_aliases(params[:search][:name_matches])

    respond_with(@tags) do |format|
      format.xml do
        render :xml => @tags.to_xml(:root => "tags")
      end
    end
  end

  def search
  end

  def show
    @tag = Tag.find(params[:id])
    respond_with(@tag)
  end

  def update
    @tag = Tag.find(params[:id])
    check_privilege(@tag)
    @tag.update_attributes(params[:tag], :as => CurrentUser.role)
    @tag.update_category_cache_for_all
    respond_with(@tag)
  end

private
  def check_privilege(tag)
    raise User::PrivilegeError unless tag.editable_by?(CurrentUser.user)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def alias_and_implication_list(antecedent_alias, consequent_aliases, antecedent_implications, consequent_implications)
    html = ""

    if antecedent_alias
      html << "<p class='hint'>This tag has been aliased to "
      html << link_to(antecedent_alias.consequent_name, show_or_new_wiki_pages_path(:title => antecedent_alias.consequent_name))
      html << ".</p>"
    end

    if consequent_aliases.any?
      html << "<p class='hint'>The following tags are aliased to this tag: "
      html << raw(consequent_aliases.map {|x| link_to(x.antecedent_name, show_or_new_wiki_pages_path(:title => x.antecedent_name))}.join(", "))
      html << ".</p>"
    end

    if antecedent_implications.any?
      html << "<p class='hint'>This tag implicates "
      html << raw(antecedent_implications.map {|x| link_to(x.consequent_name, show_or_new_wiki_pages_path(:title => x.consequent_name))}.join(", "))
      html << ".</p>"
    end

    if consequent_implications.any?
      html << "<p class='hint'>The following tags implicate this tag: "
      html << raw(consequent_implications.map {|x| link_to(x.antecedent_name, show_or_new_wiki_pages_path(:title => x.antecedent_name))}.join(", "))
      html << ".</p>"
    end

    html.html_safe
  end
  
  def tag_post_count_style(tag)
    @highest_post_count ||= Tag.highest_post_count
    width_percent = Math.log([tag.post_count, 1].max, @highest_post_count) * 100
    "background: linear-gradient(to left, #DDD #{width_percent}%, white #{width_percent}%)"
  end
end

app/views/tags/_quick_search.html.erb
<%= form_tag(tags_path, :method => :get) do %>
  <%= text_field "search", "name_matches", :id => "quick_search_name_matches", :placeholder => "Search tags" %>
<% end %>

app/views/tags/_search.html.erb
<table class="search">
  <tbody>
    <%= form_tag(tags_path, :method => :get, :class => "simple_form") do %>
      <tr>
        <th><label for="search_name_matches">Name</label></th>
        <td>
          <div class="input">
            <%= text_field "search", "name_matches", :value => params[:search][:name_matches] %>
            <span class="hint">Use * for wildcard</span>
          </div>
        </td>
      </tr>

      <tr>
        <th><label for="search_category">Category</label></th>
        <td>
          <div class="input">
            <%= select "search", "category", [""] + Danbooru.config.canonical_tag_category_mapping.to_a, :selected => params[:search][:category] %>
          </div>
        </td>
      </tr>

      <tr>
        <th><label for="search_order">Order</label></th>
        <td>
          <div class="input">
            <%= select "search", "order", %w(count date name), :selected => params[:search][:order] %>
          </div>
        </td>
      </tr>

      <tr>
        <th><label for="search_hide_empty">Hide Empty</label></th>
        <td>
          <div class="input">
            <%= select "search", "hide_empty", ["yes", "no"], :selected => params[:search][:hide_empty] %>
          </div>
        </td>
      </tr>

      <tr>
        <th><label for="search_has_wiki">Has a Wiki Page</label></th>
        <td>
          <div class="input">
            <%= select "search", "has_wiki", ["yes", "no"], :selected => params[:search][:has_wiki], :include_blank => true %>
          </div>
        </td>
      </tr>

      <tr>
        <th><label for="search_has_artist">Has an Artist Entry</label></th>
        <td>
          <div class="input">
            <%= select "search", "has_artist", ["yes", "no"], :selected => params[:search][:has_artist], :include_blank => true %>
          </div>
        </td>
      </tr>

      <tr>
        <td><%= submit_tag "Search" %><td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <menu>
    <li><%= render "tags/quick_search" %></li>
    <li><%= link_to "Listing", tags_path %></li>
    <li><%= link_to "MetaSearch", meta_searches_tags_path %></li>
    <li><%= link_to "Cheatsheet", wiki_pages_path(:search => {:title => "help:cheatsheet"}) %></li>
    <li><%= link_to "Help", wiki_pages_path(:search => {:title => "help:tags"}) %></li>
    <% if @tag %>
      <li>|</li>
      <li><%= link_to "Posts (#{Post.fast_count(@tag.name)})", posts_path(:tags => @tag.name) %></li>
      <li><%= link_to "Edit", edit_tag_path(@tag) %></li>
      <% if @tag.post_count < 1_000 %>
        <li><%= link_to "Fix", new_tag_correction_path(:tag_id => @tag.id) %></li>
      <% end %>
    <% end %>
  </menu>
<% end %>

app/views/tags/edit.html.erb
<div id="c-tags">
  <div id="a-edit">
    <h1>Tag: <%= @tag.name %></h1>

    <%= simple_form_for(@tag) do |f| %>
      <% if @tag.is_locked? %>
        <p>This tag is category locked</p>
      <% else %>
        <%= f.input :category, :collection => Danbooru.config.canonical_tag_category_mapping.to_a, :include_blank => false %>
      <% end %>

      <% if CurrentUser.is_moderator? %>
        <%= f.input :is_locked, :collection => [["No", "false"], ["Yes", "true"]], :include_blank => false %>
      <% end %>

      <%= f.button :submit, "Submit" %>
    <% end %>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Edit Tag - <%= Danbooru.config.app_name %>
<% end %>

app/views/tags/index.html.erb
<div id="c-tags">
  <div id="a-index">
    <%= render "search" %>
    <table class="striped">
      <thead>
        <tr>
          <th>Count</th>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
          <tr>
            <td style="<%= tag_post_count_style(tag) %>"><%= tag.post_count %></td>
            <td class="category-<%= tag.category %>">
              <%= link_to("?", show_or_new_wiki_pages_path(:title => tag.name)) %>
              <%= link_to(tag.name, posts_path(:tags => tag.name)) %>
            </td>
            <td>
              <% if tag.editable_by?(CurrentUser.user) %>
                <%= link_to "edit", edit_tag_path(tag) %>
              <% end %>
              <% if CurrentUser.is_builder? %>
                | <%= link_to "fix", new_tag_correction_path(:tag_id => tag.id) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= numbered_paginator(@tags) %>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Tags - <%= Danbooru.config.app_name %>
<% end %>

app/views/tags/show.html.erb
<div id="c-tags">
  <div id="a-show">
    <h1>Tag: <%= @tag.name %></h1>

    <ul>
      <li>Count: <%= @tag.post_count %></li>
      <li>Category: <%= @tag.category_name %></li>
    </ul>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Tag - <%= @tag.name %> - <%= Danbooru.config.app_name %>
<% end %>