config/routes.rb
  resources :advertisements do
    resources :hits, :controller => "advertisement_hits", :only => [:create]
  end
  resources :api_keys, :only => [:new, :create]
  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
      post :undelete
    end
    collection do
      get :show_or_new
      get :banned
      get :finder
    end
  end
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resources :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
      get :index_all
    end
    member do
      put :unvote
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :delayed_jobs, :only => [:index]
  resources :dmails do
    collection do
      get :search
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :favorites
  resources :favorite_groups do
    member do
      put :add_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :undelete
      get :new_merge
      post :create_merge
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :ip_bans
  resources :iqdb_queries, :only => [:create]
  resources :janitor_trials do
    collection do
      get :test
    end
    member do
      put :promote
      put :demote
    end
  end
  resources :jobs
  resource :landing
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource  :pool_element, :only => [:create, :destroy] do
    collection do
      get :all_select
    end
  end
  resources :pool_versions, :only => [:index]
  resources :posts do
    resources :events, :only => [:index], :controller => "post_events"
    resources :votes, :controller => "post_votes", :only => [:create, :destroy]
    collection do
      get :home
      get :random
    end
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :unvote
      put :mark_as_translated
    end
  end
  resources :post_appeals
  resources :post_flags
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index]
  resource :related_tag, :only => [:show, :update]
  get "reports/user_promotions" => "reports#user_promotions"
  get "reports/janitor_trials" => "reports#janitor_trials"
  get "reports/contributors" => "reports#contributors"
  get "reports/uploads" => "reports#uploads"
  get "reports/similar_users" => "reports#similar_users"
  get "reports/post_versions" => "reports#post_versions"
  post "reports/post_versions_create" => "reports#post_versions_create"
  resources :saved_searches, :except => [:show] do
    collection do
      get :categories
    end
  end
  resource :session do
    collection do
      get :sign_out
    end
  end
  resource :source, :only => [:show]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
    end
  end
  resources :tag_aliases do
    resource :correction, :controller => "tag_alias_corrections"
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :tag_subscriptions do
    member do
      post :migrate
      get :posts
    end
  end
  resources :uploads do
    collection do
      get :batch
      get :image_proxy
    end
  end
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"

    collection do
      get :search
      get :custom_style
    end

    member do
      delete :cache
    end
  end
  resource :user_upgrade, :only => [:new, :create, :show]
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests do
    member do
      post :approve
      post :reject
    end
  end
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"
  get "/m/posts", :controller => "mobile/posts", :action => "index"
  get "/m/posts/:id", :controller => "mobile/posts", :action => "show"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index.xml", :controller => "legacy", :action => "artists", :format => "xml"
  get "/artist/index.json", :controller => "legacy", :action => "artists", :format => "json"
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

  get "/favorite" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/index" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/list_users.json", :controller => "legacy", :action => "unavailable"

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/index" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}
  get "/forum/search" => redirect("/forum_posts/search")

  get "/help/:title" => redirect {|params, req| ("/wiki_pages?title=#{CGI::escape('help:' + req.params[:title])}")}

  get "/note" => redirect {|params, req| "/notes?page=#{req.params[:page]}"}
  get "/note/index" => redirect {|params, req| "/notes?page=#{req.params[:page]}"}
  get "/note/history" => redirect {|params, req| "/note_versions?search[updater_id]=#{req.params[:user_id]}"}

  get "/pool" => redirect {|params, req| "/pools?page=#{req.params[:page]}"}
  get "/pool/index" => redirect {|params, req| "/pools?page=#{req.params[:page]}"}
  get "/pool/show/:id" => redirect("/pools/%{id}")
  get "/pool/history/:id" => redirect("/pool_versions?search[pool_id]=%{id}")
  get "/pool/recent_changes" => redirect("/pool_versions")

  get "/post/index.xml", :controller => "legacy", :action => "posts", :format => "xml"
  get "/post/index.json", :controller => "legacy", :action => "posts", :format => "json"
  get "/post/create.xml", :controller => "legacy", :action => "create_post", :format => "xml"
  get "/post/piclens", :controller => "legacy", :action => "unavailable"
  get "/post/index" => redirect {|params, req| "/posts?tags=#{CGI::escape(req.params[:tags].to_s)}&page=#{req.params[:page]}"}
  get "/post" => redirect {|params, req| "/posts?tags=#{CGI::escape(req.params[:tags].to_s)}&page=#{req.params[:page]}"}
  get "/post/upload" => redirect("/uploads/new")
  get "/post/moderate" => redirect("/moderator/post/queue")
  get "/post/atom" => redirect {|params, req| "/posts.atom?tags=#{CGI::escape(req.params[:tags].to_s)}"}
  get "/post/atom.feed" => redirect {|params, req| "/posts.atom?tags=#{CGI::escape(req.params[:tags].to_s)}"}
  get "/post/popular_by_day" => redirect("/explore/posts/popular")
  get "/post/popular_by_week" => redirect("/explore/posts/popular")
  get "/post/popular_by_month" => redirect("/explore/posts/popular")
  get "/post/show/:id/:tag_title" => redirect("/posts/%{id}")
  get "/post/show/:id" => redirect("/posts/%{id}")
  get "/post/show" => redirect {|params, req| "/posts?md5=#{req.params[:md5]}"}
  get "/post/view/:id/:tag_title" => redirect("/posts/%{id}")
  get "/post/view/:id" => redirect("/posts/%{id}")
  get "/post/flag/:id" => redirect("/posts/%{id}")

  get("/post_tag_history" => redirect do |params, req|
    page = req.params[:before_id].present? ? "b#{req.params[:before_id]}" : req.params[:page]
    "/post_versions?page=#{page}&search[updater_id]=#{req.params[:user_id]}"
  end)

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :member_only
  before_filter :gold_only, :only => [:similar_users]
  before_filter :janitor_only, :only => [:post_versions, :post_versions_create]

  def user_promotions
    @report = Reports::UserPromotions.new
  end

  def janitor_trials
    @report = Reports::JanitorTrials.new
  end

  def contributors
    @report = Reports::Contributors.new
  end

  def uploads
    @report = Reports::Uploads.new(params[:min_date], params[:max_date], params[:queries])
  end

  def similar_users
    @report = Reports::UserSimilarity.new(CurrentUser.id)
    @presenter = UserSimilarityPresenter.new(@report)
  end

  def post_versions
  end

  def post_versions_create
    if params[:type] == "added"
      @report = Reports::PostVersionsAdded.new(params[:tag], params[:email])
    else
      @report = Reports::PostVersionsRemoved.new(params[:tag], params[:email])
    end
    @report.process!
    flash[:notice] = "Report is being generated and will be emailed to you shortly"
    redirect_to reports_post_versions_path
  end
end

app/views/reports/contributors.html.erb
<div id="c-reports">
  <div id="a-user-promotions">
    <h1>Contributor Report</h1>

    <p>Binomial proportion confidence interval for how likely a user's uploads will achieve a score of at at least n with 95% confidence within the past 30 days. Most statistics are not significant unless there are at least 300 uploads.</p>

    <table width="100%" class="striped" id="sortable">
      <thead>
        <tr>
          <th data-sort="string">User</th>
          <th data-sort="int">Level</th>
          <th data-sort="int">Uploads</th>
          <th data-sort="int">Del Chance</th>
          <th data-sort="int">Neg Score Chance</th>
        </tr>
      </thead>
      <tbody>
        <% @report.users.each do |user| %>
          <% if user.confidence_interval_for(3) > -1 %>
            <tr>
              <td><%= link_to_user user.user %></td>
              <td data-sort-value="<%= user.level %>"><%= user.level_string %></td>
              <td><%= link_to user.post_upload_count, posts_path(:tags => "user:#{user.name} order:random", :limit => 200) %></td>
              <td><%= link_to number_to_percentage(user.deletion_confidence_interval, :precision => 0), posts_path(:tags => "user:#{user.name} status:deleted", :limit => 200) %></td>
              <td><%= link_to number_to_percentage(user.negative_score_confidence_interval, :precision => 0), posts_path(:tags => "user:#{user.name} score:<0", :limit => 200) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% content_for(:page_title) do %>
  Contributor Report - <%= Danbooru.config.app_name %>
<% end %>

<%= content_for(:html_header) do %>
  <%= javascript_include_tag "stupidtable" %>
  <script type="text/javascript">
    $(function() {
      $("#sortable").stupidtable().on("aftertablesort", function() {
        $("#sortable tbody tr:even").removeClass("odd").addClass("even");
        $("#sortable tbody tr:odd").removeClass("even").addClass("odd");
      });
    });
  </script>
<% end %>

app/views/reports/janitor_trials.html.erb
<div id="c-reports">
  <div id="a-user-promotions">
    <h1>Janitor Trial Report</h1>

    <p>All numbers shown are for the past 3 months. Binomial proportion confidence interval for how likely a janitor's approvals will achieve a score of at at least n with 95% confidence. Most statistics are not significant unless there are at least 300 approvals.</p>

    <table width="100%" class="striped" id="sortable">
      <thead>
        <tr>
          <th data-sort="string">User</th>
          <th data-sort="int">Age</th>
          <th data-sort="int">Level</th>
          <th data-sort="int">Approvals</th>
          <th data-sort="int">Del Chance</th>
          <th data-sort="int">Neg Score Chance</th>
          <th data-sort="int" title="25% of approvals received this score or less">Quartile Score</th>
          <th data-sort="int" title="50% of approvals received this score or less">Median Score</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @report.janitors.each do |janitor| %>
          <tr>
            <td><%= link_to_user janitor.user %></td>
            <td data-sort-value="<%= janitor.created_at.to_i %>"><%= time_ago_in_words(janitor.created_at) %></td>
            <td data-sort-value="<%= janitor.user.level %>"><%= janitor.user.level_string %></td>
            <td><%= link_to janitor.approval_count, posts_path(:tags => "approver:#{janitor.user.name} order:random", :limit => 200) %></td>
            <td><%= link_to janitor.deletion_chance, posts_path(:tags => "approver:#{janitor.user.name} status:deleted", :limit => 200) %></td>
            <td><%= link_to janitor.neg_score_chance, posts_path(:tags => "approver:#{janitor.user.name} score:<0", :limit => 200) %></td>
            <td><%= janitor.percentile_25_score %></td>
            <td><%= janitor.percentile_50_score %></td>
            <td>
              <% if CurrentUser.user.is_moderator? && janitor.trial && janitor.trial.active? %>
                <%= link_to "Promote", promote_janitor_trial_path(janitor.trial), :method => :put, :remote => true %>
                | <%= link_to "Demote", demote_janitor_trial_path(janitor.trial), :method => :put, :remote => true %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% content_for(:page_title) do %>
  Janitor Trial Report - <%= Danbooru.config.app_name %>
<% end %>

<%= content_for(:html_header) do %>
  <%= javascript_include_tag "stupidtable" %>
  <script type="text/javascript">
    $(function() {
      $("#sortable").stupidtable().on("aftertablesort", function() {
        $("#sortable tbody tr:even").removeClass("odd").addClass("even");
        $("#sortable tbody tr:odd").removeClass("even").addClass("odd");
      });
    });
  </script>
<% end %>

app/views/reports/post_versions.html.erb
<div id="c-reports">
  <div id="a-post-versions">
    <h1>Post Changes Report</h1>

    <p>You can search all post changes to find when and where a tag was added or removed. Because these queries can take a long time to generate the results will be emailed to you. Only the 1,000 most recent changes will be returned.</p>

    <%= form_tag(reports_post_versions_create_path, :method => :post, :class => "simple_form") do %>
      <div class="input">
        <label for="tag">Tag</label>
        <%= text_field_tag "tag" %>
        <%= select_tag "type", options_for_select(%w(added removed)) %>
      </div>

      <div class="input">
        <label for="Email">Email</label>
        <%= text_field_tag "email", CurrentUser.user.email %>
      </div>

      <%= submit_tag "Submit" %>
    <% end %>

  </div>
</div>

<% content_for(:page_title) do %>
  Post Changes Report - <%= Danbooru.config.app_name %>
<% end %>

app/views/reports/similar_users.html.erb
<div id="c-reports">
  <div id="a-similar-users">
    <h1>Similar Users</h1>

    <% if @presenter.insufficient_data? %>
      <p>You need at least 200 favorites before Danbooru can calculate users similar to you.</p>

    <% elsif @presenter.not_ready? %>
      <p>The report is being generated. Check back in a few minutes.</p>

    <% else %>
      <% @presenter.each_user do |user, score| %>
        <div class="box">
          <h2><%= link_to user.pretty_name, user_path(user) %> <span class="accuracy">(<%= number_to_percentage score, :precision => 2 %>)</span></h2>
          <div>
            <% @presenter.each_favorite_for(user) do |post| %>
              <%= PostPresenter.preview(post, :tags => "fav:#{user.name}") %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<% content_for(:page_title) do %>
  Similar Users - <%= Danbooru.config.app_name %>
<% end %>

<% if @presenter.not_ready? %>
  <% content_for(:html_header) do %> 
    <meta http-equiv="refresh" content="60">
  <% end %>
<% end %>

app/views/reports/uploads.html.erb
<div id="c-reports">
  <div id="a-uploads">
    <h1>Upload Report</h1>

    <%= form_tag(reports_uploads_path, :method => :get, :class => "simple_form") do %>

      <div class="input">
        <label for="queries">Tags</label>
        <%= text_field_tag "queries", params[:queries], :placeholder => "Separate with commas" %>
      </div>

      <div class="input">
        <label for="min_date">Start Date</label>
        <%= text_field_tag "min_date", params[:min_date], :placeholder => "YYYY-MM-DD" %>
      </div>

      <div class="input">
        <label for="max_date">End Date</label>
        <%= text_field_tag "max_date", params[:max_date], :placeholder => "YYYY-MM-DD" %>
      </div>

      <%= submit_tag "Search" %>
    <% end %>

    <% if params[:queries] %>
      <%= content_tag("iframe", "Loading...", :src => "#{Danbooru.config.report_server}/reports/uploads?min=#{@report.min_date}&max=#{@report.max_date}&tags=#{u(@report.queries)}&sig=#{@report.generate_sig}", :height => "700", :width => "1200", :style => "border: none;") %>
    <% end %>
  </div>
</div>

<% content_for(:page_title) do %>
  Upload Report - <%= Danbooru.config.app_name %>
<% end %>

app/views/reports/user_promotions.html.erb
<div id="c-reports">
  <div id="a-user-promotions">
    <h1>User Promotion Report</h1>

    <p>Binomial proportion confidence interval for how likely a user's uploads will achieve a score of at at least n with 95% confidence within the past 60 days. Most statistics are not significant unless there are at least 300 uploads.</p>

    <table width="100%" class="striped" id="sortable">
      <thead>
        <tr>
          <th data-sort="string">User</th>
          <th data-sort="int">Level</th>
          <th data-sort="int">Uploads</th>
          <th data-sort="string">Age</th>
          <th data-sort="int">Del Chance</th>
          <th data-sort="int">Neg Score Chance</th>
          <th data-sort="int">Limit</th>
        </tr>
      </thead>
      <tbody>
        <% @report.users.each do |user| %>
          <% if user.confidence_interval_for(5) > 0 %>
            <tr>
              <td><%= link_to_user user.user %></td>
              <td data-sort-value="<%= user.level %>"><%= user.level_string %></td>
              <td><%= link_to user.post_upload_count, posts_path(:tags => "user:#{user.name} order:random", :limit => 200) %></td>
              <td data-sort-value="<%= user.created_at.to_formatted_s(:db) %>"><%= time_ago_in_words user.created_at %></td>
              <td><%= link_to number_to_percentage(user.deletion_confidence_interval, :precision => 0), posts_path(:tags => "user:#{user.name} status:deleted", :limit => 200) %></td>
              <td><%= link_to number_to_percentage(user.negative_score_confidence_interval, :precision => 0), posts_path(:tags => "user:#{user.name} score:<0", :limit => 200) %></td>
              <td><%= user.max_upload_limit %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% content_for(:page_title) do %>
  User Promotion Report - <%= Danbooru.config.app_name %>
<% end %>

<%= content_for(:html_header) do %>
  <%= javascript_include_tag "stupidtable" %>
  <script type="text/javascript">
    $(function() {
      $("#sortable").stupidtable().on("aftertablesort", function() {
        $("#sortable tbody tr:even").removeClass("odd").addClass("even");
        $("#sortable tbody tr:odd").removeClass("even").addClass("odd");
      });
    });
  </script>
<% end %>